# Generated by Django 5.1.4 on 2025-05-13 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('beyoung_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image3',
        ),
    ]
